import time
import random
from .rotator import KeyRotator

class NexusEngine:
    """
    Orchestrates the interaction between the User, the KeyRotator, and the LLM APIs.
    """

    def __init__(self, rotator: KeyRotator, simulation_mode: bool = True):
        self.rotator = rotator
        self.simulation_mode = simulation_mode

    def execute_prompt(self, prompt: str, stream_callback):
        """
        Main execution flow:
        1. Find a key.
        2. Send request (Mock or Real).
        3. Stream response back to UI.
        """
        
        # 1. Acquire Resource
        key_data = self.rotator.get_best_candidate()
        
        if not key_data:
            stream_callback("ERROR: KeyPool exhausted. All keys are dead or busy.", is_error=True)
            return

        model_name = key_data['model']
        provider = key_data['provider']

        # Notify UI about routing
        stream_callback(f"[System] Routing request via secure node: {provider} ({model_name})...", is_system=True)
        time.sleep(1.0) # Simulate network handshake

        # 2. Generate Response
        if self.simulation_mode:
            self._mock_generation(prompt, model_name, stream_callback)
        else:
            self._real_generation_placeholder(prompt, key_data, stream_callback)

    def _mock_generation(self, prompt: str, model_name: str, callback):
        """
        Simulates an LLM response for demonstration purposes.
        """
        response_template = (
            f"**[Response generated by {model_name}]**\n\n"
            "Based on your request, I've analyzed the project structure. "
            "Here is the optimized Python code you asked for:\n\n"
            "```python\n"
            "def optimized_algorithm(data):\n"
            "    # Vectorized operation using NumPy\n"
            "    return np.sum(data * 0.5)\n"
            "```\n\n"
            "I also detected a potential security flaw in your `auth.py`. "
            "Shall we fix it?"
        )

        for char in response_template:
            time.sleep(random.uniform(0.01, 0.04))
            callback(char)
        
        callback(None) # Signal end of stream

    def _real_generation_placeholder(self, prompt, key_data, callback):
        """
        In a production version, this would use `requests` to hit OpenAI/Anthropic APIs.
        """
        callback(f"[Error] Real API calls are disabled in this demo build. Please enable Simulation Mode in settings.yaml.", is_error=True)
        callback(None)
